@include('admin.includes.head')
@include('admin.includes.header')
@include('admin.includes.sidebar')
	@yield('content')
@include('admin.includes.footer')
	@yield('scripts')
@include('admin.includes.foot')